using System.Text.RegularExpressions;

namespace HQStudio.Setup.Core;

/// <summary>Exact secret values typed in the wizard or generated by the installer; replaced everywhere they appear.</summary>
public sealed class SecretMasker
{
    private readonly object _gate = new();
    private readonly List<string> _secrets = new();

    public void Add(string? secret)
    {
        if (string.IsNullOrEmpty(secret) || secret.Length < 4)
            return;
        lock (_gate)
        {
            if (!_secrets.Contains(secret))
                _secrets.Add(secret);
        }
    }

    public void AddRange(IEnumerable<string> secrets)
    {
        foreach (var s in secrets)
            Add(s);
    }

    public string Mask(string text)
    {
        string[] snapshot;
        lock (_gate)
            snapshot = _secrets.OrderByDescending(s => s.Length).ToArray();

        foreach (var secret in snapshot)
            text = text.Replace(secret, LogSanitizer.Redacted, StringComparison.Ordinal);
        return text;
    }
}

/// <summary>Strips secrets and personal paths from text that is written to the log or sent to GitHub.</summary>
public static class LogSanitizer
{
    public const string Redacted = "[REDACTED]";

    private static readonly TimeSpan MatchTimeout = TimeSpan.FromSeconds(3);

    private const string Keywords = @"password|passwd|pwd|secret|token|api[_-]?key|jwt[_-]?key";

    private static Regex Make(string pattern, RegexOptions extra = RegexOptions.None) =>
        new(pattern, RegexOptions.Compiled | RegexOptions.CultureInvariant | extra, MatchTimeout);

    private static readonly Regex GitHubTokens = Make(
        @"(?<![A-Za-z0-9])(?:gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})");

    private static readonly Regex BearerToken = Make(@"\bBearer\s+[A-Za-z0-9\-._~+/]+=*", RegexOptions.IgnoreCase);

    private static readonly Regex Jwt = Make(@"\beyJ[A-Za-z0-9_\-]{5,}\.[A-Za-z0-9_\-]{5,}(?:\.[A-Za-z0-9_\-]*)?");

    private static readonly Regex UrlCredentials = Make(@"(?<=://)(?<user>[^/\s:@]+):(?<pass>[^@\s/]+)@");

    private static readonly Regex KeyValue = Make(
        @"(?<![A-Za-z0-9_])(?<pre>[A-Za-z0-9_.\-]{0,40}(?:" + Keywords + @")[A-Za-z0-9_.\-]{0,40}[""']?\s*[:=]\s*)" +
        @"(?:(?<dq>""(?:[^""\\\r\n]|\\.)*"")|(?<sq>'(?:[^'\\\r\n]|\\.)*')" +
        @"|(?<semi>(?!\[REDACTED\])[^;""'\r\n]+(?=;))|(?<raw>(?!\[REDACTED\])[^\s;""',}&]+))",
        RegexOptions.IgnoreCase);

    // `docker run -e KEY=value` style and command-line flags: --password abc, --token abc
    private static readonly Regex CliFlag = Make(
        @"(?<pre>--?(?:" + Keywords + @")(?:\s+|=))(?!\[REDACTED\])(?<val>[^\s]+)", RegexOptions.IgnoreCase);

    public static string Sanitize(string? text, SecretMasker? masker = null, string? userProfile = null)
    {
        if (string.IsNullOrEmpty(text))
            return string.Empty;

        userProfile ??= Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);

        try
        {
            var result = masker?.Mask(text) ?? text;
            result = ReplaceProfilePath(result, userProfile);
            result = GitHubTokens.Replace(result, Redacted);
            result = Jwt.Replace(result, Redacted);
            result = BearerToken.Replace(result, "Bearer " + Redacted);
            result = UrlCredentials.Replace(result, "${user}:" + Redacted + "@");
            result = KeyValue.Replace(result, m =>
            {
                var pre = m.Groups["pre"].Value;
                if (m.Groups["dq"].Success) return pre + "\"" + Redacted + "\"";
                if (m.Groups["sq"].Success) return pre + "'" + Redacted + "'";
                return pre + Redacted;
            });
            result = CliFlag.Replace(result, "${pre}" + Redacted);
            return result;
        }
        catch (RegexMatchTimeoutException)
        {
            return "[content withheld: sanitizer timed out]";
        }
    }

    private static string ReplaceProfilePath(string text, string? userProfile)
    {
        if (string.IsNullOrWhiteSpace(userProfile))
            return text;

        var trimmed = userProfile.TrimEnd('\\', '/');
        if (trimmed.Length == 0)
            return text;

        var variants = new[]
        {
            trimmed,
            trimmed.Replace('\\', '/'),
            trimmed.Replace("\\", "\\\\")
        };

        foreach (var variant in variants.Distinct(StringComparer.OrdinalIgnoreCase))
        {
            var regex = new Regex(Regex.Escape(variant) + @"(?![A-Za-z0-9_])",
                RegexOptions.IgnoreCase | RegexOptions.CultureInvariant, MatchTimeout);
            text = regex.Replace(text, "%USERPROFILE%");
        }
        return text;
    }
}
